config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'patchnotes/index', to: 'patchnotes#index'

resources :projects do
    resources :patchnotes, :controller => 'patchnotes', :as => 'patchnotes'
end

resources :issues do
  resources :patch_notes, only: [:new, :create] do
    collection do
      post :skip
      post :unskip
    end
  end
end
resources :patch_notes, only: [:edit, :update, :destroy]

post 'patch_notes/bulk_skip', to: 'patch_notes#bulk_skip', as: 'bulk_skip_patch_notes'

app/models/patch_note.rb
class PatchNote < ActiveRecord::Base
  belongs_to :issue
  belongs_to :author, class_name: 'User'

  validates :part, presence: true,
            uniqueness: { scope: :issue_id, message: 'already exists for this issue' }
  validates :content, presence: true, unless: :is_skipped?
  validates :part, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :for_issue, ->(issue_id) { where(issue_id: issue_id) }
  scope :active, -> { where(is_skipped: false) }
  scope :skipped, -> { where(is_skipped: true) }
  scope :public_notes, -> { where(is_internal: false, is_skipped: false) }
  scope :internal_notes, -> { where(is_internal: true, is_skipped: false) }

  def editable_by?(user)
    return true if user.admin?
    return true if user.allowed_to?(:edit_patchnotes, issue.project)
    user.allowed_to?(:edit_own_patchnotes, issue.project) && author_id == user.id
  end
end

app/controllers/patch_notes_controller.rb
class PatchNotesController < ApplicationController
  before_action :require_login
  before_action :find_issue, only: [:new, :create, :skip, :unskip]
  before_action :find_patch_note, only: [:edit, :update, :destroy]
  before_action :authorize_edit, except: [:bulk_skip]

  def new
    unless allow_multiple_parts?
      if PatchNote.for_issue(@issue.id).active.exists?
        respond_to do |format|
          format.html { redirect_to issue_path(@issue), alert: l(:error_patch_note_single_only) }
          format.js { render js: "alert('#{j l(:error_patch_note_single_only)}');" }
        end
        return
      end
    end

    @patch_note = PatchNote.new(part: next_available_part(@issue))
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @patch_note = PatchNote.new(patch_note_params)
    @patch_note.issue = @issue
    @patch_note.author = User.current

    unless allow_multiple_parts?
      if PatchNote.for_issue(@issue.id).active.exists?
        @patch_note.errors.add(:base, l(:error_patch_note_single_only))
        respond_to do |format|
          format.html { render :new }
          format.js
        end
        return
      end
    end

    respond_to do |format|
      if @patch_note.save
        details = [{ property: 'attr', prop_key: 'patch_note', value: @patch_note.part.to_s }]
        if @patch_note.is_internal?
          details << { property: 'attr', prop_key: 'patch_note_internal', value: l(:general_text_Yes) }
        end
        log_journal(@issue, details, format_patch_note_content(@patch_note))
        format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_created) }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    old_values = { content: @patch_note.content, part: @patch_note.part, is_internal: @patch_note.is_internal }
    @patch_note.author = User.current
    respond_to do |format|
      if @patch_note.update(patch_note_params)
        details = build_update_details(old_values, @patch_note)
        log_journal(@patch_note.issue, details) if details.any?
        format.html { redirect_to issue_path(@patch_note.issue), notice: l(:notice_patch_note_updated) }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    issue = @patch_note.issue
    part = @patch_note.part
    details = [{ property: 'attr', prop_key: 'patch_note', old_value: part.to_s }]
    @patch_note.destroy
    log_journal(issue, details, format_patch_note_content(@patch_note))
    respond_to do |format|
      format.html { redirect_to issue_path(issue), notice: l(:notice_patch_note_deleted) }
      format.js { @issue = issue }
    end
  end

  def skip
    # Remove existing active patch notes for this issue first
    existing_skip = PatchNote.for_issue(@issue.id).skipped.first
    if existing_skip
      existing_skip.update(skip_reason: params[:skip_reason], author: User.current)
    else
      PatchNote.create!(
        issue: @issue,
        author: User.current,
        part: 0,
        content: '',
        is_skipped: true,
        skip_reason: params[:skip_reason]
      )
    end
    reason = params[:skip_reason].presence
    details = [{ property: 'attr', prop_key: 'patch_note_skip', value: reason || l(:general_text_Yes) }]
    log_journal(@issue, details)
    respond_to do |format|
      format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_skipped) }
      format.js
    end
  end

  def unskip
    PatchNote.for_issue(@issue.id).skipped.destroy_all
    details = [{ property: 'attr', prop_key: 'patch_note_skip', old_value: l(:general_text_Yes) }]
    log_journal(@issue, details)
    respond_to do |format|
      format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_unskipped) }
      format.js
    end
  end

  def bulk_skip
    issue_ids = Array(params[:ids]).map(&:to_i).reject(&:zero?)
    render_404 and return if issue_ids.empty?

    patchnote_tracker_ids = Tracker.where(is_patchnote: true).pluck(:id)

    issues = Issue.where(id: issue_ids)
    issues = issues.where(tracker_id: patchnote_tracker_ids) if patchnote_tracker_ids.present?

    skipped_count = 0
    issues.each do |issue|
      next if PatchNote.for_issue(issue.id).skipped.exists?

      PatchNote.create!(
        issue_id: issue.id,
        author: User.current,
        part: 0,
        content: '',
        is_skipped: true
      )
      log_journal(issue, [{ property: 'attr', prop_key: 'patch_note_skip', value: l(:general_text_Yes) }])
      skipped_count += 1
    end

    flash[:notice] = l(:notice_bulk_patch_note_skipped, count: skipped_count)
    redirect_back_or_default(home_path)
  end

  private

  def find_issue
    @issue = Issue.find(params[:issue_id])
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_patch_note
    @patch_note = PatchNote.find(params[:id])
    @issue = @patch_note.issue
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_edit
    unless @patch_note&.editable_by?(User.current) ||
           User.current.allowed_to?(:edit_patchnotes, @project) ||
           User.current.allowed_to?(:edit_own_patchnotes, @project)
      deny_access
    end
  end

  def patch_note_params
    params.require(:patch_note).permit(:part, :content, :is_internal)
  end

  def next_available_part(issue)
    existing_parts = PatchNote.for_issue(issue.id).active.pluck(:part)
    part = 1
    part += 1 while existing_parts.include?(part)
    part
  end

  def allow_multiple_parts?
    Setting[:plugin_redmine_tx_patchnotes][:allow_multiple_parts].to_s == '1'
  end

  def log_journal(issue, details, notes = '')
    issue.init_journal(User.current, notes)
    details.each do |detail_attrs|
      issue.current_journal.details.build(detail_attrs)
    end
    issue.save
  end

  def format_patch_note_content(patch_note)
    "<pre>\n#{patch_note.content}\n</pre>"
  end

  def build_update_details(old_values, patch_note)
    details = []
    if old_values[:part] != patch_note.part
      details << { property: 'attr', prop_key: 'patch_note_part', old_value: old_values[:part].to_s, value: patch_note.part.to_s }
    end
    if old_values[:is_internal] != patch_note.is_internal
      old_label = old_values[:is_internal] ? l(:general_text_Yes) : l(:general_text_No)
      new_label = patch_note.is_internal ? l(:general_text_Yes) : l(:general_text_No)
      details << { property: 'attr', prop_key: 'patch_note_internal', old_value: old_label, value: new_label }
    end
    if old_values[:content] != patch_note.content
      details << { property: 'attr', prop_key: 'patch_note_content', old_value: old_values[:content], value: patch_note.content }
    end
    details
  end
end

app/controllers/patchnotes_controller.rb
class PatchnotesController < ApplicationController
    include SortHelper
    include QueriesHelper
    include IssuesHelper
    helper :queries
    helper :sort
    helper :issues
    helper :patchnotes

      layout 'base'
      before_action :require_login
      before_action :find_project
      before_action :authorize

      def index
        @versions = Version.where("effective_date IS NOT NULL").where("effective_date > ?", Date.today - 2.month).open.order(:effective_date).to_a
        if @project
            @versions = @versions.select { |v| v.project_id == @project.id }
        end
        @versions = @versions[0..9]

        # 오늘 이후의 가장 빠른 버전을 기본값으로 설정
        @selected_version = if params[:version_id]
            version = @versions.find { |v| v.id == params[:version_id].to_i }
            version.nil? ? Version.find(params[:version_id].to_i) : version
        else
            @versions.find { |v| v.effective_date >= Date.today } || @versions.first
        end

        cache_key = compute_cache_key
        expires_in = Rails.env.development? ? 3.seconds : 5.minutes

        Rails.cache.delete(cache_key) if params[:force].present?

        cached = Rails.cache.fetch(cache_key, expires_in: expires_in) do
            process_patchnotes_data
        end

        cached.each { |k, v| instance_variable_set("@#{k}", v) }
      end

      private

      def compute_cache_key
        version_id = @selected_version.id
        pn_max = PatchNote.joins(:issue)
            .where(issues: { fixed_version_id: version_id })
            .maximum("#{PatchNote.table_name}.updated_at")
        issue_max = Issue.where(fixed_version_id: version_id).maximum(:updated_on)
        settings_digest = Digest::MD5.hexdigest(Setting[:plugin_redmine_tx_patchnotes].to_s)
        "patchnotes_#{@project.id}_#{version_id}_#{pn_max.to_i}_#{issue_max.to_i}_#{settings_digest}"
      end

      def process_patchnotes_data
        patchnote_tracker_ids = Tracker.where(is_patchnote: true).pluck(:id)
        config_complete_status = Setting[:plugin_redmine_tx_patchnotes][:complete].to_s.tr('[]" ','').split(',').map {|i| i.to_i}

        issues = Issue.where(fixed_version_id: @selected_version.id)
            .where(tracker_id: patchnote_tracker_ids)
            .where.not(status_id: IssueStatus.discarded_ids)
            .to_a

        # 상위 부모 체인 검사: is_patchnote 유형의 부모가 있으면 제거 (부모에서 패치노트 기재)
        issues.reject! { |issue|
            current = issue
            excluded = false
            while current.parent_id.present?
                current = current.parent
                if Tracker.is_patchnote?(current.tracker_id)
                    excluded = true
                    break
                end
            end
            excluded
        }

        no_patch_note_issues = []

        # redmineup_tags 플러그인이 설치된 경우 NoQA 태그가 달린 이슈를 제거
        if Redmine::Plugin.installed?(:redmineup_tags) && Issue.method_defined?(:tags)
            no_patch_note_issues = issues.select { |issue| issue.tags.map(&:name).include?(Setting[:plugin_redmine_tx_patchnotes][:patch_skip_tag]) }
            issues.reject! { |issue| no_patch_note_issues.include?(issue) }
        end

        # 미대상 유형 허용 시: 패치노트가 작성된 미대상 트래커 일감도 포함
        if Setting[:plugin_redmine_tx_patchnotes][:allow_non_target_tracker].to_s == '1'
            extra_issue_ids = PatchNote.joins(:issue)
                .where(issues: { fixed_version_id: @selected_version.id })
                .where.not(issues: { tracker_id: patchnote_tracker_ids })
                .where.not(issues: { status_id: IssueStatus.discarded_ids })
                .where.not(issue_id: issues.map(&:id))
                .pluck(:issue_id).uniq
            if extra_issue_ids.any?
                extra_issues = Issue.where(id: extra_issue_ids).to_a
                issues.concat(extra_issues)
            end
        end

        issues.sort_by! { |issue| [0 - issue.priority.position, issue.done_ratio] }

        # DB에서 패치노트 조회
        issue_ids = issues.map(&:id)
        db_notes_by_issue = PatchNote.where(issue_id: issue_ids).group_by(&:issue_id)

        notes = []
        issues.each do |issue|
            issue_notes = db_notes_by_issue[issue.id] || []

            if issue_notes.any?(&:is_skipped)
                no_patch_note_issues << issue
                next
            end

            issue_notes.select { |pn| !pn.is_skipped }.each do |pn|
                notes << { issue: issue, notes: pn.content, part: pn.part, is_internal: pn.is_internal }
            end
        end

        # 패치노트 기재 필요 없는 일감들 제거
        issues.reject! { |issue| no_patch_note_issues.include?(issue) }

        # notes에 포함된 일감들을 issues 목록에서 제거
        noted_issue_ids = notes.map { |note| note[:issue].id }.uniq

        issues_patch_note_complete = issues.select { |issue| noted_issue_ids.include?(issue.id) }
        issues_need_patch_notes = issues.select { |issue| !noted_issue_ids.include?(issue.id) && !config_complete_status.include?(issue.status_id) }
        issues_complete_without_patch_notes = issues.select { |issue| config_complete_status.include?(issue.status_id) && !noted_issue_ids.include?(issue.id) }

        # 공개용과 내부용 패치노트 분류 (DB is_internal 필드 직접 사용)
        public_notes = notes.reject { |n| n[:is_internal] }
        internal_notes = notes.select { |n| n[:is_internal] }

        worker_ids = notes.map { |n| n[:issue].respond_to?(:worker_id) ? n[:issue].worker_id : nil }.compact.uniq
        worker_users_map = worker_ids.any? ? User.where(id: worker_ids).index_by(&:id) : {}

        tracker_order = Setting[:plugin_redmine_tx_patchnotes][:tracker_order].to_s.tr('[]" ','').split(',').map(&:to_i)

        # 공개용 패치노트를 파트별로 그룹화
        public_notes_by_part = public_notes.group_by { |note| note[:part] }.sort_by { |part, _| part }
        public_notes_by_part.each do |_part, part_notes|
            part_notes.sort_by! { |note|
                tracker_id = note[:issue].tracker_id
                order_index = tracker_order.index(tracker_id)
                order_index.nil? ? 999 : order_index
            }
        end

        # 내부용 패치노트를 파트별로 그룹화
        internal_notes_by_part = internal_notes.group_by { |note| note[:part] }.sort_by { |part, _| part }
        internal_notes_by_part.each do |_part, part_notes|
            part_notes.sort_by! { |note|
                tracker_id = note[:issue].tracker_id
                order_index = tracker_order.index(tracker_id)
                order_index.nil? ? 999 : order_index
            }
        end

        {
            notes: notes,
            public_notes: public_notes,
            internal_notes: internal_notes,
            worker_users_map: worker_users_map,
            issues: issues,
            issues_patch_note_complete: issues_patch_note_complete,
            issues_need_patch_notes: issues_need_patch_notes,
            issues_complete_without_patch_notes: issues_complete_without_patch_notes,
            no_patch_note_issues: no_patch_note_issues,
            public_notes_by_part: public_notes_by_part,
            internal_notes_by_part: internal_notes_by_part,
            notes_by_part: public_notes_by_part,
        }
      end

      def find_project
        @user = params[:user_id] ? User.find(params[:user_id]) : User.current
        @project = Project.find(params[:project_id])
      rescue ActiveRecord::RecordNotFound
        render_404
      end

      def authorize
        raise Unauthorized unless User.current.allowed_to?(:view_patchnotes, @project)
      end

    end

app/helpers/patchnotes_helper.rb
module PatchnotesHelper
  TRACKER_COLORS = {
    '버그'    => '#e74c3c',
    '핫픽스'  => '#c0392b',
    '구현'    => '#3498db',
    '구현(단건)' => '#2980b9',
    '개선'    => '#27ae60',
    '설정'    => '#8e44ad',
    '번역'    => '#16a085',
    '아트리소스' => '#e67e22',
    '사운드'  => '#d35400',
    'QA'      => '#2c3e50',
    'FunQA'   => '#34495e',
  }.freeze

  TRACKER_COLOR_DEFAULT = '#7f8c8d'

  def render_issues_list(issues, project)
    query = IssueQuery.new(name: 'Patch Notes Issues')
    query.project = project
    query.column_names = [:id, :tracker, :status, :priority, :subject, :assigned_to, :done_ratio, :due_date]
    query.sort_criteria = params[:sort] if params[:sort].present?
    render partial: 'issues/list', locals: { query: query, issues: issues, context_menu: true }
  end

  def resolve_worker_name(issue, worker_users_map = {})
    if issue.respond_to?(:worker_id) && issue.worker_id.present?
      user = worker_users_map[issue.worker_id]
      return user.name.gsub(/ /, '') if user
    end
    issue.assigned_to.present? ? issue.assigned_to.name.gsub(/ /, '') : ''
  end

  def tracker_color(tracker_name)
    TRACKER_COLORS[tracker_name] || TRACKER_COLOR_DEFAULT
  end

  def tab_count_class(count, type)
    return 'pn-tab-count pn-tab-count--zero' if count == 0
    css = 'pn-tab-count pn-tab-count--'
    css + case type
          when :notes    then 'notes'
          when :complete then 'complete'
          when :exception then 'exception'
          when :missing  then 'missing'
          when :warning  then 'warning'
          else 'notes'
          end
  end
end

app/views/patch_notes/_form.html.erb
<%
  is_new = patch_note.new_record?
  url = is_new ? issue_patch_notes_path(issue) : patch_note_path(patch_note)
  method = is_new ? :post : :put
%>

<%= form_for patch_note, url: url, remote: true, html: { method: method, class: 'patch-note-form' } do |f| %>
  <% if patch_note.errors.any? %>
    <div class="flash error">
      <ul>
        <% patch_note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <label for="patch_note_part"><%= l(:field_patch_note_part) %></label>
    <%= f.select :part, (1..10).map { |i| ["Part ##{i}", i] }, {}, class: 'small' %>
  </p>

  <p>
    <label for="patch_note_content"><%= l(:field_patch_note_content) %></label>
    <%= f.text_area :content, class: 'wiki-edit', rows: 10, id: "patch_note_content_#{patch_note.id || 'new'}" %>
    <%= wikitoolbar_for("patch_note_content_#{patch_note.id || 'new'}") %>
  </p>

  <p>
    <%= f.check_box :is_internal %>
    <label for="patch_note_is_internal" class="inline"><%= l(:field_patch_note_is_internal) %></label>
  </p>

  <p>
    <%= f.submit l(:button_save), class: 'button' %>
    <% if is_new %>
      <a href="#" onclick="cancelPatchNoteForm(); return false;" class="button button-cancel"><%= l(:button_cancel) %></a>
    <% else %>
      <a href="#" onclick="cancelEditPatchNote(<%= patch_note.id %>); return false;" class="button button-cancel"><%= l(:button_cancel) %></a>
    <% end %>
  </p>
<% end %>

app/views/patch_notes/_issue_patch_note_status.html.erb
<%
  pn_settings = Setting[:plugin_redmine_tx_patchnotes]
  is_target_tracker = Tracker.is_patchnote?(issue.tracker_id)
  allow_non_target = pn_settings[:allow_non_target_tracker].to_s == '1'
  return unless is_target_tracker || allow_non_target

  patch_notes = PatchNote.for_issue(issue.id).order(:part)
  active_notes = patch_notes.active.to_a
  skip_note = patch_notes.skipped.first
  has_edit_permission = User.current.allowed_to?(:edit_patchnotes, issue.project) ||
                        User.current.allowed_to?(:edit_own_patchnotes, issue.project)
  allow_multi = pn_settings[:allow_multiple_parts].to_s == '1'
%>

<%= stylesheet_link_tag 'patch_notes', plugin: 'redmine_tx_patchnotes' %>
<%= javascript_include_tag 'patch_notes', plugin: 'redmine_tx_patchnotes' %>

<div id="patch-notes-section" class="patch-notes-section">
  <hr />
  <h3 class="patch-notes-header">
    Patch Notes
    <% if active_notes.size > 1 %>
      <span class="pn-badge pn-badge-success"><%= active_notes.size %></span>
    <% elsif active_notes.empty? && skip_note %>
      <span class="pn-badge pn-badge-skip">SKIP</span>
    <% elsif active_notes.empty? %>
      <span class="pn-badge pn-badge-none">-</span>
    <% end %>
  </h3>

  <% if active_notes.any? %>
    <% active_notes.each do |pn| %>
      <div class="patch-note-entry" id="patch-note-display-<%= pn.id %>">
        <div class="patch-note-entry-header">
          <% if pn.is_internal? %>
            <span class="pn-badge pn-badge-internal">internal</span>
          <% end %>
          <span class="patch-note-author">Part #<%= pn.part %> · <%= pn.created_at == pn.updated_at ? 'Written by' : 'Edited by' %> <%= pn.author.name %> · <%= format_time(pn.updated_at) %></span>
          <% if has_edit_permission && pn.editable_by?(User.current) %>
            <span class="patch-note-actions-inline">
              <%= link_to l(:button_edit), edit_patch_note_path(pn), remote: true, method: :get, class: 'icon icon-edit' %>
              <%= link_to l(:button_delete), patch_note_path(pn), remote: true, method: :delete,
                    data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-del' %>
            </span>
          <% end %>
        </div>
        <div class="patch-note-content wiki">
          <%= textilizable(pn.content, object: issue) %>
        </div>
      </div>
      <div id="patch-note-edit-container-<%= pn.id %>"></div>
    <% end %>
  <% end %>

  <% if skip_note %>
    <div class="patch-note-skip-info">
      <span class="pn-badge pn-badge-skip">SKIP</span>
      <span class="patch-note-skip-reason">
        <% if skip_note.skip_reason.present? %>
          <%= skip_note.skip_reason %>
        <% else %>
          <%= l(:label_patch_note_no_reason) %>
        <% end %>
      </span>
      <% if has_edit_permission %>
        <%= link_to l(:button_patch_note_unskip), skip_issue_patch_notes_path(issue), remote: true, method: :post,
              data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-reload' %>
      <% end %>
    </div>
  <% end %>

  <% if has_edit_permission && !skip_note %>
    <div id="patch-note-actions">
      <% if allow_multi || active_notes.empty? %>
        <%= link_to l(:button_patch_note_create), new_issue_patch_note_path(issue), remote: true, method: :get,
              class: 'icon icon-add button' %>
      <% end %>
      <a href="#" onclick="showSkipForm(<%= issue.id %>); return false;" class="icon icon-cancel button-skip">
        <%= l(:button_patch_note_skip) %>
      </a>
    </div>

    <div id="patch-note-skip-form-container" style="display:none;">
      <%= form_tag skip_issue_patch_notes_path(issue), remote: true, method: :post do %>
        <div class="patch-note-skip-form">
          <label for="skip_reason"><%= l(:field_patch_note_skip_reason) %></label>
          <%= text_field_tag :skip_reason, '', class: 'full-width', placeholder: l(:text_patch_note_skip_placeholder) %>
          <div class="patch-note-form-actions">
            <%= submit_tag l(:button_save), class: 'button' %>
            <a href="#" onclick="hideSkipForm(); return false;" class="button button-cancel"><%= l(:button_cancel) %></a>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div id="patch-note-form-container"></div>
</div>

app/views/patch_notes/create.js.erb
<% if @patch_note.errors.any? %>
$('#patch-note-form-container').html('<%= j render partial: "patch_notes/form", locals: { patch_note: @patch_note, issue: @issue } %>');
<% else %>
window.location.reload();
<% end %>

app/views/patch_notes/destroy.js.erb
window.location.reload();

app/views/patch_notes/edit.js.erb
$('#patch-note-display-<%= @patch_note.id %>').hide();
$('#patch-note-edit-container-<%= @patch_note.id %>').html('<%= j render partial: "patch_notes/form", locals: { patch_note: @patch_note, issue: @issue } %>');
$('#patch-note-edit-container-<%= @patch_note.id %>').show();

app/views/patch_notes/new.js.erb
$('#patch-note-form-container').html('<%= j render partial: "patch_notes/form", locals: { patch_note: @patch_note, issue: @issue } %>');
$('#patch-note-form-container').show();
$('#patch-note-actions').hide();

app/views/patch_notes/skip.js.erb
window.location.reload();

app/views/patch_notes/unskip.js.erb
window.location.reload();

app/views/patch_notes/update.js.erb
<% if @patch_note.errors.any? %>
$('#patch-note-edit-container-<%= @patch_note.id %>').html('<%= j render partial: "patch_notes/form", locals: { patch_note: @patch_note, issue: @issue } %>');
<% else %>
window.location.reload();
<% end %>