config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'patchnotes/index', to: 'patchnotes#index'

resources :projects do
    resources :patchnotes, :controller => 'patchnotes', :as => 'patchnotes'
end

resources :issues do
  resources :patch_notes, only: [:new, :create] do
    collection do
      post :skip
      post :unskip
    end
  end
end
resources :patch_notes, only: [:edit, :update, :destroy]

post 'patch_notes/bulk_skip', to: 'patch_notes#bulk_skip', as: 'bulk_skip_patch_notes'

app/models/patch_note.rb
class PatchNote < ActiveRecord::Base
  belongs_to :issue
  belongs_to :author, class_name: 'User'

  validates :part, presence: true,
            uniqueness: { scope: :issue_id, message: 'already exists for this issue' }
  validates :content, presence: true, unless: :is_skipped?
  validates :part, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :for_issue, ->(issue_id) { where(issue_id: issue_id) }
  scope :active, -> { where(is_skipped: false) }
  scope :skipped, -> { where(is_skipped: true) }
  scope :public_notes, -> { where(is_internal: false, is_skipped: false) }
  scope :internal_notes, -> { where(is_internal: true, is_skipped: false) }

  def editable_by?(user)
    return true if user.admin?
    return true if user.allowed_to?(:edit_patchnotes, issue.project)
    user.allowed_to?(:edit_own_patchnotes, issue.project) && author_id == user.id
  end
end

app/controllers/patch_notes_controller.rb
class PatchNotesController < ApplicationController
  before_action :require_login
  before_action :find_issue, only: [:new, :create, :skip, :unskip]
  before_action :find_patch_note, only: [:edit, :update, :destroy]
  before_action :authorize_edit, except: [:bulk_skip]

  def new
    unless allow_multiple_parts?
      if PatchNote.for_issue(@issue.id).active.exists?
        respond_to do |format|
          format.html { redirect_to issue_path(@issue), alert: l(:error_patch_note_single_only) }
          format.js { render js: "alert('#{j l(:error_patch_note_single_only)}');" }
        end
        return
      end
    end

    @patch_note = PatchNote.new(part: next_available_part(@issue))
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @patch_note = PatchNote.new(patch_note_params)
    @patch_note.issue = @issue
    @patch_note.author = User.current

    unless allow_multiple_parts?
      if PatchNote.for_issue(@issue.id).active.exists?
        @patch_note.errors.add(:base, l(:error_patch_note_single_only))
        respond_to do |format|
          format.html { render :new }
          format.js
        end
        return
      end
    end

    respond_to do |format|
      if @patch_note.save
        details = [{ property: 'attr', prop_key: 'patch_note', value: @patch_note.part.to_s }]
        if @patch_note.is_internal?
          details << { property: 'attr', prop_key: 'patch_note_internal', value: l(:general_text_Yes) }
        end
        log_journal(@issue, details, format_patch_note_content(@patch_note))
        format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_created) }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    old_values = { content: @patch_note.content, part: @patch_note.part, is_internal: @patch_note.is_internal }
    @patch_note.author = User.current
    respond_to do |format|
      if @patch_note.update(patch_note_params)
        details = build_update_details(old_values, @patch_note)
        log_journal(@patch_note.issue, details) if details.any?
        format.html { redirect_to issue_path(@patch_note.issue), notice: l(:notice_patch_note_updated) }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    issue = @patch_note.issue
    part = @patch_note.part
    details = [{ property: 'attr', prop_key: 'patch_note', old_value: part.to_s }]
    @patch_note.destroy
    log_journal(issue, details, format_patch_note_content(@patch_note))
    respond_to do |format|
      format.html { redirect_to issue_path(issue), notice: l(:notice_patch_note_deleted) }
      format.js { @issue = issue }
    end
  end

  def skip
    # Remove existing active patch notes for this issue first
    existing_skip = PatchNote.for_issue(@issue.id).skipped.first
    if existing_skip
      existing_skip.update(skip_reason: params[:skip_reason], author: User.current)
    else
      PatchNote.create!(
        issue: @issue,
        author: User.current,
        part: 0,
        content: '',
        is_skipped: true,
        skip_reason: params[:skip_reason]
      )
    end
    reason = params[:skip_reason].presence
    details = [{ property: 'attr', prop_key: 'patch_note_skip', value: reason || l(:general_text_Yes) }]
    log_journal(@issue, details)
    respond_to do |format|
      format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_skipped) }
      format.js
    end
  end

  def unskip
    PatchNote.for_issue(@issue.id).skipped.destroy_all
    details = [{ property: 'attr', prop_key: 'patch_note_skip', old_value: l(:general_text_Yes) }]
    log_journal(@issue, details)
    respond_to do |format|
      format.html { redirect_to issue_path(@issue), notice: l(:notice_patch_note_unskipped) }
      format.js
    end
  end

  def bulk_skip
    issue_ids = Array(params[:ids]).map(&:to_i).reject(&:zero?)
    render_404 and return if issue_ids.empty?

    patchnote_tracker_ids = Tracker.where(is_patchnote: true).pluck(:id)

    issues = Issue.where(id: issue_ids)
    issues = issues.where(tracker_id: patchnote_tracker_ids) if patchnote_tracker_ids.present?

    skipped_count = 0
    issues.each do |issue|
      next if PatchNote.for_issue(issue.id).skipped.exists?

      PatchNote.create!(
        issue_id: issue.id,
        author: User.current,
        part: 0,
        content: '',
        is_skipped: true
      )
      log_journal(issue, [{ property: 'attr', prop_key: 'patch_note_skip', value: l(:general_text_Yes) }])
      skipped_count += 1
    end

    flash[:notice] = l(:notice_bulk_patch_note_skipped, count: skipped_count)
    redirect_back_or_default(home_path)
  end

  private

  def find_issue
    @issue = Issue.find(params[:issue_id])
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_patch_note
    @patch_note = PatchNote.find(params[:id])
    @issue = @patch_note.issue
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_edit
    unless @patch_note&.editable_by?(User.current) ||
           User.current.allowed_to?(:edit_patchnotes, @project) ||
           User.current.allowed_to?(:edit_own_patchnotes, @project)
      deny_access
    end
  end

  def patch_note_params
    params.require(:patch_note).permit(:part, :content, :is_internal)
  end

  def next_available_part(issue)
    existing_parts = PatchNote.for_issue(issue.id).active.pluck(:part)
    part = 1
    part += 1 while existing_parts.include?(part)
    part
  end

  def allow_multiple_parts?
    Setting[:plugin_redmine_tx_patchnotes][:allow_multiple_parts].to_s == '1'
  end

  def log_journal(issue, details, notes = '')
    issue.init_journal(User.current, notes)
    details.each do |detail_attrs|
      issue.current_journal.details.build(detail_attrs)
    end
    issue.save
  end

  def format_patch_note_content(patch_note)
    "<pre>\n#{patch_note.content}\n</pre>"
  end

  def build_update_details(old_values, patch_note)
    details = []
    if old_values[:part] != patch_note.part
      details << { property: 'attr', prop_key: 'patch_note_part', old_value: old_values[:part].to_s, value: patch_note.part.to_s }
    end
    if old_values[:is_internal] != patch_note.is_internal
      old_label = old_values[:is_internal] ? l(:general_text_Yes) : l(:general_text_No)
      new_label = patch_note.is_internal ? l(:general_text_Yes) : l(:general_text_No)
      details << { property: 'attr', prop_key: 'patch_note_internal', old_value: old_label, value: new_label }
    end
    if old_values[:content] != patch_note.content
      details << { property: 'attr', prop_key: 'patch_note_content', old_value: old_values[:content], value: patch_note.content }
    end
    details
  end
end

app/controllers/patchnotes_controller.rb
class PatchnotesController < ApplicationController
    include SortHelper
    include QueriesHelper
    include IssuesHelper
    helper :queries
    helper :sort
    helper :issues
    helper :patchnotes

      layout 'base'
      before_action :require_login
      before_action :find_project
      before_action :authorize

      def index
        @versions = Version.where("effective_date IS NOT NULL").where("effective_date > ?", Date.today - 2.month).open.order(:effective_date).to_a
        if @project
            @versions = @versions.select { |v| v.project_id == @project.id }
        end
        @versions = @versions[0..9]

        # 오늘 이후의 가장 빠른 버전을 기본값으로 설정
        @selected_version = if params[:version_id]
            version = @versions.find { |v| v.id == params[:version_id].to_i }
            version.nil? ? Version.find(params[:version_id].to_i) : version
        else
            @versions.find { |v| v.effective_date >= Date.today } || @versions.first
        end

        cache_key = compute_cache_key
        expires_in = Rails.env.development? ? 3.seconds : 5.minutes

        Rails.cache.delete(cache_key) if params[:force].present?

        cached = Rails.cache.fetch(cache_key, expires_in: expires_in) do
            process_patchnotes_data
        end

        cached.each { |k, v| instance_variable_set("@#{k}", v) }
      end

      private

      def compute_cache_key
        version_id = @selected_version.id
        pn_max = PatchNote.joins(:issue)
            .where(issues: { fixed_version_id: version_id })
            .maximum("#{PatchNote.table_name}.updated_at")
        issue_max = Issue.where(fixed_version_id: version_id).maximum(:updated_on)
        settings_digest = Digest::MD5.hexdigest(Setting[:plugin_redmine_tx_patchnotes].to_s)
        "patchnotes_#{@project.id}_#{version_id}_#{pn_max.to_i}_#{issue_max.to_i}_#{settings_digest}"
      end

      def process_patchnotes_data
        patchnote_tracker_ids = Tracker.where(is_patchnote: true).pluck(:id)
        config_complete_status = Setting[:plugin_redmine_tx_patchnotes][:complete].to_s.tr('[]" ','').split(',').map {|i| i.to_i}

        issues = Issue.where(fixed_version_id: @selected_version.id)
            .where(tracker_id: patchnote_tracker_ids)
            .where.not(status_id: IssueStatus.discarded_ids)
            .to_a

        # 상위 부모 체인 검사: is_patchnote 유형의 부모가 있으면 제거 (부모에서 패치노트 기재)
        issues.reject! { |issue|
            current = issue
            excluded = false
            while current.parent_id.present?
                current = current.parent
                if Tracker.is_patchnote?(current.tracker_id)
                    excluded = true
                    break
                end
            end
            excluded
        }

        no_patch_note_issues = []

        # redmineup_tags 플러그인이 설치된 경우 NoQA 태그가 달린 이슈를 제거
        if Redmine::Plugin.installed?(:redmineup_tags) && Issue.method_defined?(:tags)
            no_patch_note_issues = issues.select { |issue| issue.tags.map(&:name).include?(Setting[:plugin_redmine_tx_patchnotes][:patch_skip_tag]) }
            issues.reject! { |issue| no_patch_note_issues.include?(issue) }
        end

        # 미대상 유형 허용 시: 패치노트가 작성된 미대상 트래커 일감도 포함
        if Setting[:plugin_redmine_tx_patchnotes][:allow_non_target_tracker].to_s == '1'
            extra_issue_ids = PatchNote.joins(:issue)
                .where(issues: { fixed_version_id: @selected_version.id })
                .where.not(issues: { tracker_id: patchnote_tracker_ids })
                .where.not(issues: { status_id: IssueStatus.discarded_ids })
                .where.not(issue_id: issues.map(&:id))
                .pluck(:issue_id).uniq
            if extra_issue_ids.any?
                extra_issues = Issue.where(id: extra_issue_ids).to_a
                issues.concat(extra_issues)
            end
        end

        issues.sort_by! { |issue| [0 - issue.priority.position, issue.done_ratio] }

        # DB에서 패치노트 조회
        issue_ids = issues.map(&:id)
        db_notes_by_issue = PatchNote.where(issue_id: issue_ids).group_by(&:issue_id)

        notes = []
        issues.each do |issue|
            issue_notes = db_notes_by_issue[issue.id] || []

            if issue_notes.any?(&:is_skipped)
                no_patch_note_issues << issue
                next
            end

            issue_notes.select { |pn| !pn.is_skipped }.each do |pn|
                notes << { issue: issue, notes: pn.content, part: pn.part, is_internal: pn.is_internal }
            end
        end

        # 패치노트 기재 필요 없는 일감들 제거
        issues.reject! { |issue| no_patch_note_issues.include?(issue) }

        # notes에 포함된 일감들을 issues 목록에서 제거
        noted_issue_ids = notes.map { |note| note[:issue].id }.uniq

        issues_patch_note_complete = issues.select { |issue| noted_issue_ids.include?(issue.id) }
        issues_need_patch_notes = issues.select { |issue| !noted_issue_ids.include?(issue.id) && !config_complete_status.include?(issue.status_id) }
        issues_complete_without_patch_notes = issues.select { |issue| config_complete_status.include?(issue.status_id) && !noted_issue_ids.include?(issue.id) }

        # 공개용과 내부용 패치노트 분류 (DB is_internal 필드 직접 사용)
        public_notes = notes.reject { |n| n[:is_internal] }
        internal_notes = notes.select { |n| n[:is_internal] }

        worker_ids = notes.map { |n| n[:issue].respond_to?(:worker_id) ? n[:issue].worker_id : nil }.compact.uniq
        worker_users_map = worker_ids.any? ? User.where(id: worker_ids).index_by(&:id) : {}

        tracker_order = Setting[:plugin_redmine_tx_patchnotes][:tracker_order].to_s.tr('[]" ','').split(',').map(&:to_i)

        # 공개용 패치노트를 파트별로 그룹화
        public_notes_by_part = public_notes.group_by { |note| note[:part] }.sort_by { |part, _| part }
        public_notes_by_part.each do |_part, part_notes|
            part_notes.sort_by! { |note|
                tracker_id = note[:issue].tracker_id
                order_index = tracker_order.index(tracker_id)
                order_index.nil? ? 999 : order_index
            }
        end

        # 내부용 패치노트를 파트별로 그룹화
        internal_notes_by_part = internal_notes.group_by { |note| note[:part] }.sort_by { |part, _| part }
        internal_notes_by_part.each do |_part, part_notes|
            part_notes.sort_by! { |note|
                tracker_id = note[:issue].tracker_id
                order_index = tracker_order.index(tracker_id)
                order_index.nil? ? 999 : order_index
            }
        end

        {
            notes: notes,
            public_notes: public_notes,
            internal_notes: internal_notes,
            worker_users_map: worker_users_map,
            issues: issues,
            issues_patch_note_complete: issues_patch_note_complete,
            issues_need_patch_notes: issues_need_patch_notes,
            issues_complete_without_patch_notes: issues_complete_without_patch_notes,
            no_patch_note_issues: no_patch_note_issues,
            public_notes_by_part: public_notes_by_part,
            internal_notes_by_part: internal_notes_by_part,
            notes_by_part: public_notes_by_part,
        }
      end

      def find_project
        @user = params[:user_id] ? User.find(params[:user_id]) : User.current
        @project = Project.find(params[:project_id])
      rescue ActiveRecord::RecordNotFound
        render_404
      end

      def authorize
        raise Unauthorized unless User.current.allowed_to?(:view_patchnotes, @project)
      end

    end

app/helpers/patchnotes_helper.rb
module PatchnotesHelper
  TRACKER_COLORS = {
    '버그'    => '#e74c3c',
    '핫픽스'  => '#c0392b',
    '구현'    => '#3498db',
    '구현(단건)' => '#2980b9',
    '개선'    => '#27ae60',
    '설정'    => '#8e44ad',
    '번역'    => '#16a085',
    '아트리소스' => '#e67e22',
    '사운드'  => '#d35400',
    'QA'      => '#2c3e50',
    'FunQA'   => '#34495e',
  }.freeze

  TRACKER_COLOR_DEFAULT = '#7f8c8d'

  def render_issues_list(issues, project)
    query = IssueQuery.new(name: 'Patch Notes Issues')
    query.project = project
    query.column_names = [:id, :tracker, :status, :priority, :subject, :assigned_to, :done_ratio, :due_date]
    query.sort_criteria = params[:sort] if params[:sort].present?
    render partial: 'issues/list', locals: { query: query, issues: issues, context_menu: true }
  end

  def resolve_worker_name(issue, worker_users_map = {})
    if issue.respond_to?(:worker_id) && issue.worker_id.present?
      user = worker_users_map[issue.worker_id]
      return user.name.gsub(/ /, '') if user
    end
    issue.assigned_to.present? ? issue.assigned_to.name.gsub(/ /, '') : ''
  end

  def tracker_color(tracker_name)
    TRACKER_COLORS[tracker_name] || TRACKER_COLOR_DEFAULT
  end

  def tab_count_class(count, type)
    return 'pn-tab-count pn-tab-count--zero' if count == 0
    css = 'pn-tab-count pn-tab-count--'
    css + case type
          when :notes    then 'notes'
          when :complete then 'complete'
          when :exception then 'exception'
          when :missing  then 'missing'
          when :warning  then 'warning'
          else 'notes'
          end
  end
end

app/views/patchnotes/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'context_menu' %>
    <%= javascript_include_tag 'context_menu' %>
    <%= stylesheet_link_tag 'scm' %>
    <%= stylesheet_link_tag 'wiki' %>
    <%= stylesheet_link_tag 'patch_notes', plugin: 'redmine_tx_patchnotes' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.2/html2pdf.bundle.min.js"></script>
    <%= javascript_include_tag 'patchnotes_index', plugin: 'redmine_tx_patchnotes' %>
<% end %>
<style>
  #content .tabs.tabs-wrap { height: auto; overflow: visible; }
  #content .tabs.tabs-wrap ul { position: static; min-width: 0; display: flex; flex-wrap: wrap; }
  #content .tabs.tabs-wrap ul li { margin-bottom: 4px; }
</style>
<div class="tabs tabs-wrap">
    <ul>
        <% @versions.each do |version| %>
            <li><%= link_to version.name.to_s, '?version_id=' + version.id.to_s, class: @selected_version.id == version.id ? 'selected' : '' %></li>
        <% end %>
    </ul>
</div>

<% active_tab = params[:tab] || '1' %>
<% total_notes = @public_notes.count + @internal_notes.count %>

<div class="pn-content-tabs" data-version-name="<%= @selected_version.name %>">
    <ul>
        <li>
            <a href="#" class="tab-link <%= active_tab == '1' ? 'active' : '' %>" data-tab="inner-tab-1">
                패치노트
                <span class="<%= tab_count_class(total_notes, :notes) %>"><%= total_notes %></span>
            </a>
        </li>
        <li>
            <a href="#" class="tab-link <%= active_tab == '2' ? 'active' : '' %>" data-tab="inner-tab-2">
                작성 완료
                <span class="<%= tab_count_class(@issues_patch_note_complete.count, :complete) %>"><%= @issues_patch_note_complete.count %></span>
            </a>
        </li>
        <li>
            <a href="#" class="tab-link <%= active_tab == '3' ? 'active' : '' %>" data-tab="inner-tab-3">
                예외
                <span class="<%= tab_count_class(@no_patch_note_issues.count, :exception) %>"><%= @no_patch_note_issues.count %></span>
            </a>
        </li>
        <li>
            <a href="#" class="tab-link <%= active_tab == '4' ? 'active' : '' %>" data-tab="inner-tab-4">
                누락
                <span class="<%= tab_count_class(@issues_need_patch_notes.count, :missing) %>"><%= @issues_need_patch_notes.count %></span>
            </a>
        </li>
        <li>
            <a href="#" class="tab-link <%= active_tab == '5' ? 'active' : '' %>" data-tab="inner-tab-5">
                미기재 완료
                <span class="<%= tab_count_class(@issues_complete_without_patch_notes.count, :warning) %>"><%= @issues_complete_without_patch_notes.count %></span>
            </a>
        </li>
    </ul>
</div>

<div>
    <%# === Tab 1: Patch Notes === %>
    <div id="inner-tab-1" class="tab-panel <%= active_tab == '1' ? 'active' : '' %>">

        <% if @public_notes.empty? && @internal_notes.empty? %>
            <div class="pn-empty-state">
                <span class="pn-empty-state-icon">&#128196;</span>
                이 버전에 작성된 패치노트가 없습니다.
            </div>
        <% end %>

        <% if @public_notes.any? %>
            <h2 class="pn-section-header--public">공개용 패치노트 (<%= @public_notes.count %>)</h2>

            <% allow_multi = Setting[:plugin_redmine_tx_patchnotes][:allow_multiple_parts].to_s == '1' %>
            <% @public_notes_by_part.each do |part, notes| %>
                <div class="pn-part-header">
                    <h3 class="pn-part-title">Part <%= part %>/<%= @public_notes_by_part.size %></h3>
                    <div class="pn-part-actions">
                        <a href="#" onclick="exportPatchNotesToPdf(<%= part %>, 'public'); return false;" class="icon icon-download button">PDF</a>
                        <a href="#" onclick="exportPatchNotesToExcel(<%= part %>, 'public'); return false;" class="icon icon-download button">엑셀</a>
                        <a href="#" onclick="copyPatchNotes(<%= part %>, 'public'); return false;" class="icon icon-copy button">복사</a>
                    </div>
                </div>
                <div class="version-box">
                    <ul class="patch-notes-list-public-<%= part %>" id="patch-notes-list-public-<%= part %>">
                        <% notes.each do |note| %>
                            <% worker_name = resolve_worker_name(note[:issue], @worker_users_map) %>
                            <li class="note-item"
                                style="border-left-color: <%= tracker_color(note[:issue].tracker.name) %>;"
                                data-issue-id="<%= note[:issue].id %>"
                                data-issue-url="<%= issue_url(note[:issue]) %>"
                                data-tracker="<%= note[:issue].tracker.name %>"
                                data-category="<%= note[:issue].category.present? ? note[:issue].category.name : '' %>"
                                data-status="<%= note[:issue].status.name %>"
                                data-priority="<%= note[:issue].priority.name %>"
                                data-done-ratio="<%= note[:issue].done_ratio %>"
                                data-assignee="<%= worker_name %>">
                                <div class="note-item-header">
                                    <span class="pn-tracker-badge" style="background-color: <%= tracker_color(note[:issue].tracker.name) %>;"><%= note[:issue].tracker.name %></span>
                                    <strong class="note-item-title">
                                        <%= note[:issue].subject %> <%= link_to "##{note[:issue].id}", issue_path(note[:issue]) %>
                                    </strong>
                                    <% if worker_name.present? %>
                                        <span class="pn-assignee-tag"><%= worker_name %></span>
                                    <% end %>
                                </div>
                                <div class="note-item-content wiki">
                                    <%= textilizable(note[:notes], :object => note[:issue]) %>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        <% end %>

        <% if @internal_notes.any? %>
            <h2 class="pn-section-header--internal">내부 참조용 패치노트 (<%= @internal_notes.count %>)</h2>
            <p class="pn-internal-warning">이 섹션의 패치노트는 유저 공개용 패치노트에 포함되지 않습니다.</p>

            <% @internal_notes_by_part.each do |part, notes| %>
                <div class="pn-part-header">
                    <h3 class="pn-part-title">내부 Part <%= part %>/<%= @internal_notes_by_part.size %></h3>
                    <div class="pn-part-actions">
                        <a href="#" onclick="exportPatchNotesToPdf(<%= part %>, 'internal'); return false;" class="icon icon-download button">PDF</a>
                        <a href="#" onclick="exportPatchNotesToExcel(<%= part %>, 'internal'); return false;" class="icon icon-download button">엑셀</a>
                        <a href="#" onclick="copyPatchNotes(<%= part %>, 'internal'); return false;" class="icon icon-copy button">복사</a>
                    </div>
                </div>
                <div class="version-box version-box--internal">
                    <ul class="patch-notes-list-internal-<%= part %>" id="patch-notes-list-internal-<%= part %>">
                        <% notes.each do |note| %>
                            <% worker_name = resolve_worker_name(note[:issue], @worker_users_map) %>
                            <li class="note-item"
                                style="border-left-color: <%= tracker_color(note[:issue].tracker.name) %>;"
                                data-issue-id="<%= note[:issue].id %>"
                                data-issue-url="<%= issue_url(note[:issue]) %>"
                                data-tracker="<%= note[:issue].tracker.name %>"
                                data-category="<%= note[:issue].category.present? ? note[:issue].category.name : '' %>"
                                data-status="<%= note[:issue].status.name %>"
                                data-priority="<%= note[:issue].priority.name %>"
                                data-done-ratio="<%= note[:issue].done_ratio %>"
                                data-assignee="<%= worker_name %>">
                                <div class="note-item-header">
                                    <span class="pn-tracker-badge" style="background-color: <%= tracker_color(note[:issue].tracker.name) %>;"><%= note[:issue].tracker.name %></span>
                                    <strong class="note-item-title">
                                        <%= note[:issue].subject %> <%= link_to "##{note[:issue].id}", issue_path(note[:issue]) %>
                                    </strong>
                                    <% if worker_name.present? %>
                                        <span class="pn-assignee-tag"><%= worker_name %></span>
                                    <% end %>
                                </div>
                                <div class="note-item-content wiki">
                                    <%= textilizable(note[:notes], :object => note[:issue]) %>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        <% end %>

    </div>

    <%# === Tab 2: Issues with patch notes complete === %>
    <div id="inner-tab-2" class="tab-panel <%= active_tab == '2' ? 'active' : '' %>">
        <h3>패치노트 작성 완료 일감</h3>
        <% if @issues_patch_note_complete.any? %>
            <div class="version-box">
                <%= render_issues_list(@issues_patch_note_complete, @project) %>
            </div>
        <% else %>
            <div class="pn-empty-state">
                <span class="pn-empty-state-icon">&#9989;</span>
                패치노트 작성이 완료된 일감이 없습니다.
            </div>
        <% end %>
    </div>

    <%# === Tab 3: Issues excluded from patch notes === %>
    <div id="inner-tab-3" class="tab-panel <%= active_tab == '3' ? 'active' : '' %>">
        <h3>패치노트 작성 예외 일감</h3>
        <% if @no_patch_note_issues.any? %>
            <div class="version-box">
                <%= render_issues_list(@no_patch_note_issues, @project) %>
            </div>
        <% else %>
            <div class="pn-empty-state">
                <span class="pn-empty-state-icon">&#128683;</span>
                패치노트 작성 예외 처리된 일감이 없습니다.
            </div>
        <% end %>
    </div>

    <%# === Tab 4: Issues missing patch notes === %>
    <div id="inner-tab-4" class="tab-panel <%= active_tab == '4' ? 'active' : '' %>">
        <h3>패치노트 누락 일감</h3>
        <% if @issues_need_patch_notes.any? %>
            <div class="version-box">
                <%= render_issues_list(@issues_need_patch_notes, @project) %>
            </div>
        <% else %>
            <div class="pn-empty-state">
                <span class="pn-empty-state-icon">&#127881;</span>
                모든 일감의 패치노트가 작성되었습니다.
            </div>
        <% end %>
    </div>

    <%# === Tab 5: Completed without patch notes === %>
    <div id="inner-tab-5" class="tab-panel <%= active_tab == '5' ? 'active' : '' %>">
        <h3>패치노트 기재 없이 완료 처리된 일감</h3>
        <% if @issues_complete_without_patch_notes.any? %>
            <div class="version-box">
                <%= render_issues_list(@issues_complete_without_patch_notes, @project) %>
            </div>
        <% else %>
            <div class="pn-empty-state">
                <span class="pn-empty-state-icon">&#128077;</span>
                패치노트 없이 완료된 일감이 없습니다.
            </div>
        <% end %>
    </div>
</div>

<%= context_menu %>